---
title: "BST 260 - Final Project"
subtitle: "In-person Presidential campaign rallies and trends in country-level COVID-19 cases and deaths"
authors: "Daniel Arias, Kritika Anand, and Tianxiao Zhao"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{R}
knitr::opts_chunk$set(echo = TRUE)

```

To-Do List
1) Kritika -- add county fips numbers to rallies.csv -- https://www.nrcs.usda.gov/wps/portal/nrcs/detail/national/home/?cid=nrcs143_013697
2) Daniel -- loading updated rallies.csv to dataframe
3) Daniel -- fix choropleth data
4) All -- next week, work on centering time data around rallies (before and after), start visualizations of time series data

```{r}

## Load Libraries
library(tidyverse)
library(dplyr)
library(lubridate)
library(foreach)
library(ggplot2)
library(maps)
library(viridis)
library(zoo)


## Directory and file paths 
path <- "~/3. PhD/Y2/Fall/BST 260/bst-260-final-project-covid19-rallies/"
outputpath <- paste(path,'results/', sep = "/")
datapath <- paste(path,'data/', sep = "/")




```

## Step 1: Prepare COVID-19 Data

```{r Load Data,  include=FALSE}

## Step 1a: Import Case Dataset 
cases <- read_csv(file = file.path(datapath,"time_series_covid19_confirmed_US.csv")) %>%
  mutate(state_fips = as.numeric(substr(FIPS,1,2))) %>%
  mutate(county_fips = as.numeric(substr(FIPS,3,5))) %>%
  mutate(fips = as.numeric(FIPS)) %>%
  drop_na(fips) %>%
  select(-UID, -iso2, -iso3, -code3, -Country_Region, -FIPS) %>%
  filter(Province_State != "American Samoa", 
         Province_State != 'Puerto Rico',
         Province_State != "Guam", 
         Province_State != "Northern Mariana Islands", 
         Province_State != "Virgin Islands", 
         Province_State != 'Diamond Princess', 
         Province_State != 'Grand Princess', 
         Admin2 != "Unassigned") %>% 
  rename(county_name = Admin2, 
         state_name = Province_State, 
         lat = Lat, 
         long = Long_, 
         full_name = Combined_Key ) %>%
  pivot_longer(contains("/"), names_to = "date", values_to = "cases") %>%
  mutate(date = as.Date(date, "%m/%d/%y"))

## Step 1b: Import Death Dataset 
deaths <- read_csv(file = file.path(datapath,"time_series_covid19_deaths_US.csv")) %>%
  mutate(fips = as.numeric(FIPS)) %>%
  drop_na(fips) %>%
  filter(Province_State != "American Samoa", 
         Province_State != 'Puerto Rico',
         Province_State != "Guam", 
         Province_State != "Northern Mariana Islands", 
         Province_State != "Virgin Islands", 
         Province_State != 'Diamond Princess', 
         Province_State != 'Grand Princess',
         Admin2 != "Unassigned") %>% 
  select(-UID, -iso2, -iso3, -code3, -Country_Region, -FIPS, -Lat, -Long_, -Province_State, -Combined_Key, -Admin2) %>%
  pivot_longer(contains("/"), names_to = "date", values_to = "deaths") %>%
  mutate(date = as.Date(date, "%m/%d/%y"))

## Step 1c: Merge the data together 
df <- cases %>%
  left_join(deaths, by = c('fips','date')) %>%
  arrange(fips, date)

rm(cases, deaths)

## Step 1d: Load US Census Data - By Race
load("~/3. PhD/Y2/Fall/BST 260/bst-260-final-project-covid19-rallies/data/cc-est2019-alldata.RData")

racial_demographics <- cc %>%
  rename_all(.funs = tolower) %>%
  filter(year == 12) %>% ## 2019
  filter(agegrp == 0) %>% ## Totals only 
  mutate(black_pop = ba_male + ba_female, 
         white_pop = wa_male + wa_female, 
         asian_pop = aa_male + aa_female, 
         native_pop = ia_male + ia_female, 
         pacific_pop = na_male + na_female, 
         hisp_pop = h_male + h_female) %>%
  select(state_fips = state, 
         county_fips = county, 
         county_name_long = ctyname,
         total_pop = tot_pop,
         black_pop, white_pop, asian_pop, native_pop,  pacific_pop, hisp_pop)

## Step 1e: Load US Census Data - By Age 
age_demographics <- cc %>%
  rename_all(.funs = tolower) %>%
  filter(year == 12) %>% ## 2019
  filter(agegrp > 13) %>% ## Keep if 65 or older
  select(state_fips = state, 
         county_fips = county, 
         total_pop = tot_pop) %>%
  group_by(state_fips, county_fips) %>%
  summarise(senior_pop = sum(total_pop))
  
## Step 1f: Merge Demographic Info with Case and Death Counts
df <- df %>%
  left_join(racial_demographics, by=c('state_fips','county_fips')) %>%
  left_join(age_demographics, by=c('state_fips','county_fips')) 

rm(racial_demographics, age_demographics)

## Step 1g: Load US Mobility data
mobility <- read_csv(file = file.path(datapath,"DL-us-mobility-daterow.csv")) %>%
  rename_all(.funs = tolower) %>%
  mutate(fips = as.numeric(fips)) %>%
  drop_na(admin1) %>%
  drop_na(admin2) %>%
  select(date, fips, m_samples = samples, m50, m50_index) 

## Step 1h: Merge Mobility Info with Full Dataset
df <- df %>%
  left_join(mobility, by = c('fips','date')) %>%
  arrange(fips, date)

rm(mobility)

## Step 1i: Load Median Income 
income <- read_csv(file = file.path(datapath,"nhgis0014_ds239_20185_2018_county_E.csv")) %>%
  select(median_inc = AJZAE001, state_name = STATE, county_name_long = COUNTY)

## Step 1j: Merge Median Income Info with Full Dataset
df <- df %>%
  left_join(income, by = c('state_name','county_name_long'))

rm(income)
rm(cc)
```

## Step 2: Summary Statistics and visualizations

```{r basic visualization }

df <- df[-c(3:4)] #Cleaning data to drop columns that are not needed
df <- rename(df, "population" = "Population")

########CASES

# Creating a variable that contains the number of new confirmed cases
df <- df %>% 
  arrange(date) %>% 
  group_by(fips)  %>% 
  mutate(new_cases = cases - lag(cases))

# Creating a rolling 7-day average for the number of new confirmed cases
df <- df %>% 
  arrange(date) %>% 
  group_by(fips) %>% 
  mutate(new_cases_7dayavg = rollmean(new_cases, k = 7, fill = NA))


# Creating a new variable that calculates the seven-day rolling average of new cases per million
df <- df %>% 
  mutate(new_cases_7dayavg_per_mil_cap = new_cases_7dayavg / population * 1000000)

######### DEATHS

# Creating a variable that contains the number of new confirmed cases
df <- df %>% 
  arrange(date) %>% 
  group_by(fips)  %>% 
  mutate(new_deaths = deaths - lag(deaths))

# Creating a rolling 7-day average for the number of new confirmed deaths
df <- df %>% 
  arrange(date) %>% 
  group_by(fips) %>% 
  mutate(new_deaths_7dayavg = rollmean(new_deaths, k = 7, fill = NA))


# Creating a new variable that calculates the seven-day rolling average of new deaths per million
df <- df %>% 
  mutate(new_deaths_7dayavg_per_mil_cap = new_deaths_7dayavg / population * 1000000)
```


```{R}
# ADD RALLY DATA HERE -- COULD FOLKS DO THE FOLLOWING
# Add code to load in rally csv
# Filter out rallies that predate February 26, 2020 (first community spread in February 26)
# Full join rally and df by fips
# Drop unnecessary duplicate columns to save data space
# Drop the rally database using the rm() function after merging (to save memory)
# Make sure dates of rallies are saved as.date
# Create a binary indicator (1,0) for whether the county held a rally (on any date)
# Among counties that held a rally, create a variable which is the number of days before and after a rally

  # You can use the date between function (e.g., if a rally happens on Oct. 10, the value for this variable for a given county on Oct. 9 should be -1.
  # For October 11, it should be 1). This variable will be the x axis that we can use to plot all rally counties together (we are centering them by the 
  # date of the rallies)

```

```{R}

# Downloading map data
us_map = map_data("county")
fips <- data.frame(county.fips)
us_map$polyname <- paste(us_map$region, us_map$subregion, sep = ",")
us_map <- full_join(fips, us_map, by = "polyname")

```


```{R}
# Merging map data into dataframe

df <- full_join(df, us_map, by = c("fips"))
rm(us_map)
rm(fips)

```



```{R}


df %>% filter(date == "2020-08-01") %>%
   ggplot(aes(x = long, y = lat, group = group, fill = new_cases_7dayavg_per_mil_cap)) +
      geom_polygon() + 
      theme(panel.grid.major = element_blank(), 
            panel.background = element_blank(),
            axis.title = element_blank(), 
            axis.text = element_blank(),
            axis.ticks = element_blank()) +
      labs(title="Number of new confirmed COVID-19 cases per million people",
        subtitle="on August 1, 2020",
        caption="Source: Center for Systems Science and Engineering, Johns Hopkins University",
        fill="Rolling 7-day average") +
   scale_fill_viridis_c(option = "plasma",
                               limits = c(0,300),    # Forcing upper limit of 300 cases per million capita per day
                               oob = scales::squish) # Letting values out of bounds be squished to scale

df %>% filter(date == "2020-10-01") %>%
   ggplot(aes(x = long, y = lat, group = group, fill = new_cases_7dayavg)) +
      geom_polygon() + 
      theme(panel.grid.major = element_blank(), 
            panel.background = element_blank(),
            axis.title = element_blank(), 
            axis.text = element_blank(),
            axis.ticks = element_blank()) +
      labs(title="Number of new confirmed COVID-19 cases",
        subtitle="on October 1, 2020",
        caption="Source: Center for Systems Science and Engineering, Johns Hopkins University",
        fill="Rolling 7-day average") +
   scale_fill_viridis_c(option = "plasma",
                               limits = c(0,150),    # Forcing upper limit of 150 cases per day
                               oob = scales::squish) # Letting values out of bounds be squished to scale

df %>% filter(date == "2020-10-01") %>%
   ggplot(aes(x = long, y = lat, group = group, fill = deaths)) +
      geom_polygon() + 
      theme(panel.grid.major = element_blank(), 
            panel.background = element_blank(),
            axis.title = element_blank(), 
            axis.text = element_blank(),
            axis.ticks = element_blank()) +
      labs(title="Number of cumulative COVID-19 deaths",
        subtitle="as of October 1, 2020",
        caption="Source: Center for Systems Science and Engineering, Johns Hopkins University",
        fill="Cumulative deaths") +
   scale_fill_viridis_c(option = "plasma",
                               limits = c(0,1000),    # Forcing upper limit of 1000 deaths
                               oob = scales::squish) # Letting values out of bounds be squished to scale


df %>% filter(date == "2020-08-01") %>%
   ggplot(aes(x = long, y = lat, group = group, fill = new_deaths_7dayavg_per_mil_cap)) +
      geom_polygon() + 
      theme(panel.grid.major = element_blank(), 
            panel.background = element_blank(),
            axis.title = element_blank(), 
            axis.text = element_blank(),
            axis.ticks = element_blank()) +
      labs(title="Number of new confirmed COVID-19 deaths per million people",
        subtitle="on August 1, 2020",
        caption="Source: Center for Systems Science and Engineering, Johns Hopkins University",
        fill="Rolling 7-day average") +
   scale_fill_viridis_c(option = "plasma",
                               limits = c(0,100),    # Forcing upper limit of 100 deaths per million capita per day
                               oob = scales::squish) # Letting values out of bounds be squished to scale

df %>% filter(date == "2020-08-01") %>%
   ggplot(aes(x = long, y = lat, group = group, fill = new_deaths_7dayavg)) +
      geom_polygon() + 
      theme(panel.grid.major = element_blank(), 
            panel.background = element_blank(),
            axis.title = element_blank(), 
            axis.text = element_blank(),
            axis.ticks = element_blank()) +
      labs(title="Number of new confirmed COVID-19 deaths",
        subtitle="on August 1, 2020",
        caption="Source: Center for Systems Science and Engineering, Johns Hopkins University",
        fill="Rolling 7-day average") +
   scale_fill_viridis_c(option = "plasma",
                               limits = c(0,100),    # Forcing upper limit of 100 deaths per day
                               oob = scales::squish) # Letting values out of bounds be squished to scale

df %>% filter(date == "2020-08-01") %>%
   ggplot(aes(x = long, y = lat, group = group, fill = total_pop)) +
      geom_polygon() + 
      theme(panel.grid.major = element_blank(), 
            panel.background = element_blank(),
            axis.title = element_blank(), 
            axis.text = element_blank(),
            axis.ticks = element_blank()) +
      labs(title="Total population",
        caption="Source: US Census Bureau",
        fill="Population size") +
   scale_fill_viridis_c(option = "plasma",
                               limits = c(0,1000000),    # Forcing upper limit of 1,000,000 pop
                               oob = scales::squish) # Letting values out of bounds be squished to scale
```

```{R}

# Code for adding circles that identify where rallies were located
# geom_point(data=d, aes(x=lon, y=lat), color="red", size=30, alpha=0.5)

```
